### ISSUE TITLE
Polymer 2.0 support

### ISSUE THREAD

**Issue by NicolasRannou** [oyeharry/app-menu#1]
Any plan to upgrade it to polymer 2.0.? That would be awesome, pretty cool element.

**Comment by oyeharry** [comment]
Yes, the support is coming soon. Thanks!

**Comment by NicolasRannou** [comment]
FYI seems that the paper-menu/submenu is being deprecated in Polymer 2.0 in favor of listbox..
```
Thanks for the PR! Unfortunately, we did not port this element deliberately, since it's deprecated in favour of paper-listbox, which has been ported already.
```
https://github.com/PolymerElements/paper-menu/pull/113

**Comment by oyeharry** [comment]
Added hybrid support on `2.0-preview` branch.
