### ISSUE TITLE
Prevent submenus from closing

### ISSUE THREAD

**Issue by brettpostin** [oyeharry/app-menu#3]
Hey, great element. Really fills the gap for the deprecated paper-menu element.

Is there a way to prevent a submenu from closing when selecting an item in the parent menu?

Behaviour demonstrated in [official demo](https://www.webcomponents.org/element/oyeharry/app-menu/demo/demo/index.html).

**Comment by oyeharry** [comment]
I have been thinking about it. I will add an option soon. Thanks!

**Comment by NenadJovicic** [comment]
Is there an option to choose that auto close is active?
