### ISSUE TITLE
App-menu in paper-menu-button

### ISSUE THREAD

**Issue by NenadJovicic** [oyeharry/app-menu#7]
I am trying to use your component inside paper-menu-button component.
I forked your project and put `app-menu` as `dropdown-content` of menu button.
Is it possible somehow to reset everything about `app-menu` (to return everything to default) when dropdown is closed?
Because, if I select something in `app-submenu`, dropdown will be closed after click. And when I open dropdown again, app-submenu is opened because I select something inside it. But what I want is when I open dropdown again that everything is closed and nothing is selected.

Link to my forked project where you can see example: https://github.com/NenadJovicic/app-menu

**Comment by oyeharry** [comment]
There is no such functionality which can reset all `app-menu` after closing `paper-menu-button`. However, you can do using your own script.
